# Generated by Django 2.2.3 on 2019-11-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='map',
            name='token',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='ссылка'),
        ),
    ]
